# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Никита/Desktop/GUI/satellite.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(789, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_all = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_all.setOrientation(QtCore.Qt.Vertical)
        self.splitter_all.setObjectName("splitter_all")
        self.splitter_map_prop_res = QtWidgets.QSplitter(self.splitter_all)
        self.splitter_map_prop_res.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_map_prop_res.setObjectName("splitter_map_prop_res")
        self.splitter_map_prop = QtWidgets.QSplitter(self.splitter_map_prop_res)
        self.splitter_map_prop.setOrientation(QtCore.Qt.Vertical)
        self.splitter_map_prop.setObjectName("splitter_map_prop")
        self.gridLayoutWidget = QtWidgets.QWidget(self.splitter_map_prop)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid_map = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid_map.setContentsMargins(0, 0, 0, 0)
        self.grid_map.setObjectName("grid_map")
        self.groupBox_map = QtWidgets.QGroupBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_map.sizePolicy().hasHeightForWidth())
        self.groupBox_map.setSizePolicy(sizePolicy)
        self.groupBox_map.setMinimumSize(QtCore.QSize(530, 400))
        self.groupBox_map.setSizeIncrement(QtCore.QSize(470, 452))
        self.groupBox_map.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_map.setObjectName("groupBox_map")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_map)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.grid_map.addWidget(self.groupBox_map, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.splitter_map_prop)
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.grid_properties = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.grid_properties.setContentsMargins(0, 0, 0, 0)
        self.grid_properties.setObjectName("grid_properties")
        self.groupBox_properties = QtWidgets.QGroupBox(self.gridLayoutWidget_2)
        self.groupBox_properties.setMinimumSize(QtCore.QSize(257, 56))
        self.groupBox_properties.setBaseSize(QtCore.QSize(470, 70))
        self.groupBox_properties.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_properties.setObjectName("groupBox_properties")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_properties)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_mode = QtWidgets.QPushButton(self.groupBox_properties)
        self.button_mode.setObjectName("button_mode")
        self.horizontalLayout_2.addWidget(self.button_mode)
        self.button_clear = QtWidgets.QPushButton(self.groupBox_properties)
        self.button_clear.setObjectName("button_clear")
        self.horizontalLayout_2.addWidget(self.button_clear)
        self.grid_properties.addWidget(self.groupBox_properties, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.splitter_map_prop_res)
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.grid_results = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.grid_results.setContentsMargins(0, 0, 0, 0)
        self.grid_results.setObjectName("grid_results")
        self.groupBox_results = QtWidgets.QGroupBox(self.gridLayoutWidget_3)
        self.groupBox_results.setMinimumSize(QtCore.QSize(220, 450))
        self.groupBox_results.setBaseSize(QtCore.QSize(310, 530))
        self.groupBox_results.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_results.setObjectName("groupBox_results")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_results)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_fire = QtWidgets.QLabel(self.groupBox_results)
        self.label_fire.setMinimumSize(QtCore.QSize(200, 200))
        self.label_fire.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_fire.setText("")
        self.label_fire.setObjectName("label_fire")
        self.verticalLayout.addWidget(self.label_fire)
        self.label_cloud = QtWidgets.QLabel(self.groupBox_results)
        self.label_cloud.setMinimumSize(QtCore.QSize(200, 200))
        self.label_cloud.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_cloud.setText("")
        self.label_cloud.setObjectName("label_cloud")
        self.verticalLayout.addWidget(self.label_cloud)
        self.grid_results.addWidget(self.groupBox_results, 0, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.splitter_all)
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.grid_buttons = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.grid_buttons.setContentsMargins(0, 0, 0, 0)
        self.grid_buttons.setObjectName("grid_buttons")
        self.groupBox_buttons = QtWidgets.QGroupBox(self.gridLayoutWidget_4)
        self.groupBox_buttons.setMinimumSize(QtCore.QSize(382, 56))
        self.groupBox_buttons.setBaseSize(QtCore.QSize(788, 94))
        self.groupBox_buttons.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_buttons.setObjectName("groupBox_buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_buttons)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_analyze = QtWidgets.QPushButton(self.groupBox_buttons)
        self.button_analyze.setObjectName("button_analyze")
        self.horizontalLayout.addWidget(self.button_analyze)
        self.button_save = QtWidgets.QPushButton(self.groupBox_buttons)
        self.button_save.setObjectName("button_save")
        self.horizontalLayout.addWidget(self.button_save)
        self.button_exit = QtWidgets.QPushButton(self.groupBox_buttons)
        self.button_exit.setObjectName("button_exit")
        self.horizontalLayout.addWidget(self.button_exit)
        self.grid_buttons.addWidget(self.groupBox_buttons, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.splitter_all, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Satellite images processing"))
        self.groupBox_map.setTitle(_translate("MainWindow", "     Map     "))
        self.groupBox_properties.setTitle(_translate("MainWindow", "Map Properties"))
        self.button_mode.setText(_translate("MainWindow", "Offline mode"))
        self.button_clear.setText(_translate("MainWindow", "Clear marker"))
        self.groupBox_results.setTitle(_translate("MainWindow", "Results of models"))
        self.groupBox_buttons.setTitle(_translate("MainWindow", "Buttons"))
        self.button_analyze.setText(_translate("MainWindow", "Analyze"))
        self.button_save.setText(_translate("MainWindow", "Save"))
        self.button_exit.setText(_translate("MainWindow", "Exit"))

